In [9]:
#importing libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import sqlite3

In [10]:
#uploading the data
df1 = pd.read_csv("data/Content (1).csv")
df2 = pd.read_csv("data/Reactions (1).csv")
df3 = pd.read_csv("data/ReactionTypes (1).csv")

In [11]:
df1

,Unnamed: 0,Content ID,User ID,Type,Category,URL
0,0,97522e57-d9ab-4bd6-97bf-c24d952602d2,8d3cd87d-8a31-4935-9a4f-b319bfe05f31,photo,Studying,https://socialbuzz.cdn.com/content/storage/975...
1,1,9f737e0a-3cdd-4d29-9d24-753f4e3be810,beb1f34e-7870-46d6-9fc7-2e12eb83ce43,photo,healthy eating,https://socialbuzz.cdn.com/content/storage/9f7...
2,2,230c4e4d-70c3-461d-b42c-ec09396efb3f,a5c65404-5894-4b87-82f2-d787cbee86b4,photo,healthy eating,https://socialbuzz.cdn.com/content/storage/230...
3,3,356fff80-da4d-4785-9f43-bc1261031dc6,9fb4ce88-fac1-406c-8544-1a899cee7aaf,photo,technology,https://socialbuzz.cdn.com/content/storage/356...
4,4,01ab84dd-6364-4236-abbb-3f237db77180,e206e31b-5f85-4964-b6ea-d7ee5324def1,video,food,https://socialbuzz.cdn.com/content/storage/01a...
...,...,...,...,...,...,...
995,995,b4cef9ef-627b-41d7-a051-5961b0204ebb,5b62e10e-3c19-4d28-a57c-e9bdc3d6758d,video,public speaking,NaN
996,996,7a79f4e4-3b7d-44dc-bdef-bc990740252c,4fe420fa-a193-4408-bd5d-62a020233609,GIF,technology,https://socialbuzz.cdn.com/content/storage/7a7...
997,997,435007a5-6261-4d8b-b0a4-55fdc189754b,35d6a1f3-e358-4d4b-8074-05f3b7f35c2a,audio,veganism,https://socialbuzz.cdn.com/content/storage/435...
998,998,4e4c9690-c013-4ee7-9e66-943d8cbd27b7,b9bcd994-f000-4f6b-87fc-caae08acfaa1,GIF,culture,https://socialbuzz.cdn.com/content/storage/4e4...
999,999,75d6b589-7fae-4a6d-b0d0-752845150e56,b8c653b5-0118-4d7e-9bde-07c2de90f0ff,audio,technology,https://socialbuzz.cdn.com/content/storage/75d...

```markdown
### Cleaning df1

In this step, we will clean the `df1` dataframe by dropping unnecessary columns and handling any missing values or inconsistencies. This will help us prepare the data for further analysis.
```

In [12]:

df1 = df1.drop(columns=['URL'])

df1

,Unnamed: 0,Content ID,User ID,Type,Category
0,0,97522e57-d9ab-4bd6-97bf-c24d952602d2,8d3cd87d-8a31-4935-9a4f-b319bfe05f31,photo,Studying
1,1,9f737e0a-3cdd-4d29-9d24-753f4e3be810,beb1f34e-7870-46d6-9fc7-2e12eb83ce43,photo,healthy eating
2,2,230c4e4d-70c3-461d-b42c-ec09396efb3f,a5c65404-5894-4b87-82f2-d787cbee86b4,photo,healthy eating
3,3,356fff80-da4d-4785-9f43-bc1261031dc6,9fb4ce88-fac1-406c-8544-1a899cee7aaf,photo,technology
4,4,01ab84dd-6364-4236-abbb-3f237db77180,e206e31b-5f85-4964-b6ea-d7ee5324def1,video,food
...,...,...,...,...,...
995,995,b4cef9ef-627b-41d7-a051-5961b0204ebb,5b62e10e-3c19-4d28-a57c-e9bdc3d6758d,video,public speaking
996,996,7a79f4e4-3b7d-44dc-bdef-bc990740252c,4fe420fa-a193-4408-bd5d-62a020233609,GIF,technology
997,997,435007a5-6261-4d8b-b0a4-55fdc189754b,35d6a1f3-e358-4d4b-8074-05f3b7f35c2a,audio,veganism
998,998,4e4c9690-c013-4ee7-9e66-943d8cbd27b7,b9bcd994-f000-4f6b-87fc-caae08acfaa1,GIF,culture
999,999,75d6b589-7fae-4a6d-b0d0-752845150e56,b8c653b5-0118-4d7e-9bde-07c2de90f0ff,audio,technology

In [13]:
df1 = df1.rename(columns={'Type': 'Content Type'})
df1 = df1.drop(columns=['User ID'])
df1

,Unnamed: 0,Content ID,Content Type,Category
0,0,97522e57-d9ab-4bd6-97bf-c24d952602d2,photo,Studying
1,1,9f737e0a-3cdd-4d29-9d24-753f4e3be810,photo,healthy eating
2,2,230c4e4d-70c3-461d-b42c-ec09396efb3f,photo,healthy eating
3,3,356fff80-da4d-4785-9f43-bc1261031dc6,photo,technology
4,4,01ab84dd-6364-4236-abbb-3f237db77180,video,food
...,...,...,...,...
995,995,b4cef9ef-627b-41d7-a051-5961b0204ebb,video,public speaking
996,996,7a79f4e4-3b7d-44dc-bdef-bc990740252c,GIF,technology
997,997,435007a5-6261-4d8b-b0a4-55fdc189754b,audio,veganism
998,998,4e4c9690-c013-4ee7-9e66-943d8cbd27b7,GIF,culture
999,999,75d6b589-7fae-4a6d-b0d0-752845150e56,audio,technology

In [14]:
# Check for blanks in df1
print("Missing values in df1:")
print(df1.isnull().sum())

Missing values in df1:
Unnamed: 0      0
Content ID      0
Content Type    0
Category        0
dtype: int64

In [15]:
# Remove surrounding quotes and strip whitespace from relevant columns
df1['Content ID'] = df1['Content ID'].str.strip().str.replace('"', '')


# Check for duplicates
duplicates = df1[df1.duplicated()]
print("Duplicates in df1:")
print(duplicates)

Duplicates in df1:
Empty DataFrame
Columns: [Unnamed: 0, Content ID, Content Type, Category]
Index: []

```markdown
### Cleaning df2

In this step, we will clean the `df2` dataframe by dropping unnecessary columns, handling any missing values, and ensuring data consistency. This will help us prepare the data for further analysis.
```

In [16]:
# Remove surrounding quotes and strip whitespace from relevant columns
df2['Content ID'] = df2['Content ID'].str.strip().str.replace('"', '')
df2['User ID'] = df2['User ID'].str.strip().str.replace('"', '')

# Check for blanks in df2
df2 = df2.dropna(subset=['User ID', 'Type'])
print("Missing values in df2:")
print(df2.isnull().sum())
df2
df2.info()
df2 = df2.drop(columns=['User ID'])

Missing values in df2:
Unnamed: 0    0
Content ID    0
User ID       0
Type          0
Datetime      0
dtype: int64
<class 'pandas.core.frame.DataFrame'>
Index: 22534 entries, 1 to 25552
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  22534 non-null  int64
 1   Content ID  22534 non-null  object
 2   User ID     22534 non-null  object
 3   Type        22534 non-null  object
 4   Datetime    22534 non-null  object
dtypes: int64(1), object(4)
memory usage: 1.0+ MB

In [17]:
# Merge df1 and df2 on 'Content ID'
merged_df = pd.merge(df1, df2, on='Content ID')

# Merge the result with df3 on 'Type'
final_df = pd.merge(merged_df, df3, on='Type')

# Calculate the total scores for each category
category_scores = final_df.groupby('Category')['Score'].sum().reset_index()

# Get the top 5 performing categories
top_5_categories = category_scores.nlargest(5, 'Score')

# Drop unnamed columns
final_df = final_df.loc[:, ~final_df.columns.str.contains('^Unnamed')]

# Display the top 5 categories
print("Top 5 performing categories:")
print(top_5_categories)

# Save the top 5 categories to a CSV file
top_5_categories.to_csv("data/top_5_categories.csv", index=False)

# Display the final dataframe
final_df

Top 5 performing categories:
          Category  Score
24         animals  63544
31  healthy eating  62866
36      technology  61879
33         science  60575
25         cooking  58530

,Content ID,Content Type,Category,Type,Datetime,Sentiment,Score
0,97522e57-d9ab-4bd6-97bf-c24d952602d2,photo,Studying,disgust,2020-11-07 09:43:50,negative,0
1,97522e57-d9ab-4bd6-97bf-c24d952602d2,photo,Studying,dislike,2021-06-17 12:22:51,negative,10
2,97522e57-d9ab-4bd6-97bf-c24d952602d2,photo,Studying,scared,2021-04-18 05:13:58,negative,15
3,97522e57-d9ab-4bd6-97bf-c24d952602d2,photo,Studying,disgust,2021-01-06 19:13:01,negative,0
4,97522e57-d9ab-4bd6-97bf-c24d952602d2,photo,Studying,interested,2020-08-23 12:25:58,positive,30
...,...,...,...,...,...,...,...
22529,75d6b589-7fae-4a6d-b0d0-752845150e56,audio,technology,worried,2020-10-31 04:50:14,negative,12
22530,75d6b589-7fae-4a6d-b0d0-752845150e56,audio,technology,dislike,2020-06-27 09:46:48,negative,10
22531,75d6b589-7fae-4a6d-b0d0-752845150e56,audio,technology,intrigued,2021-02-16 17:17:02,positive,45
22532,75d6b589-7fae-4a6d-b0d0-752845150e56,audio,technology,worried,2020-11-04 20:08:31,negative,12
22533,75d6b589-7fae-4a6d-b0d0-752845150e56,audio,technology,cherish,2021-01-04 04:55:11,positive,70

In [18]:
# Save the final_df dataframe as a CSV file
final_df.to_csv("data/final_dataframe.csv", index=False)

In [19]:
# Merge final_df with top_5_categories on 'Category'
merged_top_5_df = pd.merge(final_df, top_5_categories, on='Category', suffixes=('_final', '_top5'))

# Display the merged dataframe
print(merged_top_5_df)

                                Content ID Content Type        Category  \
0     9f737e0a-3cdd-4d29-9d24-753f4e3be810        photo  healthy eating
1     9f737e0a-3cdd-4d29-9d24-753f4e3be810        photo  healthy eating
2     9f737e0a-3cdd-4d29-9d24-753f4e3be810        photo  healthy eating
3     9f737e0a-3cdd-4d29-9d24-753f4e3be810        photo  healthy eating
4     9f737e0a-3cdd-4d29-9d24-753f4e3be810        photo  healthy eating
...                                    ...          ...             ...
7732  75d6b589-7fae-4a6d-b0d0-752845150e56        audio      technology
7733  75d6b589-7fae-4a6d-b0d0-752845150e56        audio      technology
7734  75d6b589-7fae-4a6d-b0d0-752845150e56        audio      technology
7735  75d6b589-7fae-4a6d-b0d0-752845150e56        audio      technology
7736  75d6b589-7fae-4a6d-b0d0-752845150e56        audio      technology

           Type             Datetime Sentiment  Score_final  Score_top5
0       dislike  2020-06-25 17:01:58  negative           10       62866
1     intrigued  2020-09-13 00:11:50  positive           45       62866
2       peeking  2020-08-20 18:17:06   neutral           35       62866
3        scared  2021-02-11 04:53:56  negative           15       62866
4          hate  2021-03-08 10:40:53  negative            5       62866
...         ...                  ...       ...          ...         ...
7732    worried  2020-10-31 04:50:14  negative           12       61879
7733    dislike  2020-06-27 09:46:48  negative           10       61879
7734  intrigued  2021-02-16 17:17:02  positive           45       61879
7735    worried  2020-11-04 20:08:31  negative           12       61879
7736    cherish  2021-01-04 04:55:11  positive           70       61879

[7737 rows x 8 columns]

In [20]:
# Save the merged_top_5_df dataframe as a CSV file
merged_top_5_df.to_csv("data/merged_top_5_dataframe.csv", index=False)